### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by Zonr0** [legitbiz/SealsOfFate#121]
From: https://github.com/psu-oss-2017/psu-oss-2017.github.io/wiki/project-reqs

- [ ] Developer Names
- [ ] Project Name
- [ ] Contact Information/bug tracker
- [ ] Legal
   - [ ] Copyright notices on everything
   - [ ] License Information on everything
   - [ ] A COPYING file containing copyright and license information
- [ ] User and/or developer docs sufficient to let end users work with the software and/or developers understand it. Recommended process: Write something minimal, then have someone else review it to find places where it is insufficient. Repeat as needed.
- [ ] Source code
   - [ ] Optionally binaries, but consistency with SCMS and platform make this a bad idea unless it's unlikely that your users could build the software. Good example is Android apps, for which you'll need a current .apk.
   - [ ] Tags in the SCMS for "stable" commits.
- [ ] Build instructions
   - [ ] Checkout and download insns
   - [ ] Prerequisites for build
   - [ ] Build instructions
   - [ ] Installation instructions
